### ISSUE TITLE
tapioca init failing with Rails 8.0.2 - Generating RBI files of gems that are added or updated

### ISSUE THREAD

**Issue by mattbee** [Shopify/tapioca#2339]
## Issue

I've tried to add Sorbet/tapioca to 2 projects now to have a play, and it has produced the same error when running `tapioca init`, both on the step `Generating RBI files of gems that are added or updated`:
```
'Tapioca::Loaders::Loader#load_engines_in_zeitwerk_mode': undefined method 'flat_map' for an instance of Zeitwerk::Registry::Loaders (NoMethodError)

        managed_dirs = Zeitwerk::Registry.loaders.flat_map(&:dirs).to_set
```
(full stack trace below)

## Steps to reproduce

1. Create a simple rails project with Rails 8.0.2
2. Add sorbet and tapioca gems
3. run `bundle install`
4. run `bundle exec tapioca init`

I wouldn't have reported aside from it happened on 2 different projects, one a virtually clean Rails 8.0.2 app, which has halted any progress altogether (for a talk on how easy it is to intergate sorbet, ironically...). Everything worked on an old project with Rails 7.1.3 however.

## Environment
- Macbook Pro Apple M4
- Rails 8.0.2
- Bundler version 2.6.9

## Full stack trace

1. 
```
mattbee /Users/mattbee/projects/thing ~(mb-add-sorbet) $ bundle exec tapioca init
      create  sorbet/config
      create  sorbet/tapioca/config.yml
      create  sorbet/tapioca/require.rb
      create  bin/tapioca
Retrieving index from central repository... Done
Listing gems from Gemfile.lock... Done
Removing annotations for gems that have been removed...  Nothing to do
Fetching gem annotations from central repository... 

  Fetched actionmailer
      create  sorbet/rbi/annotations/actionmailer.rbi

  Fetched actionpack
      create  sorbet/rbi/annotations/actionpack.rbi

  Fetched actionview
      create  sorbet/rbi/annotations/actionview.rbi

  Fetched activejob
      create  sorbet/rbi/annotations/activejob.rbi

  Fetched activemodel
      create  sorbet/rbi/annotations/activemodel.rbi

  Fetched activerecord
      create  sorbet/rbi/annotations/activerecord.rbi

  Fetched activesupport
      create  sorbet/rbi/annotations/activesupport.rbi

  Fetched globalid
      create  sorbet/rbi/annotations/globalid.rbi

  Fetched minitest
      create  sorbet/rbi/annotations/minitest.rbi

  Fetched railties
      create  sorbet/rbi/annotations/railties.rbi

  Fetched rainbow
      create  sorbet/rbi/annotations/rainbow.rbi

Done
Removing RBI files of gems that have been removed:

  Nothing to do.

Generating RBI files of gems that are added or updated:

Requiring all gems to prepare for compiling... bundler: failed to load command: tapioca (/Users/mattbee/.gem/ruby/3.4.2/bin/tapioca)
/Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/loader.rb:116:in 'Tapioca::Loaders::Loader#load_engines_in_zeitwerk_mode': undefined method 'flat_map' for an instance of Zeitwerk::Registry::Loaders (NoMethodError)

        managed_dirs = Zeitwerk::Registry.loaders.flat_map(&:dirs).to_set
                                                 ^^^^^^^^^
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Loader#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/loader.rb:96:in 'block in Tapioca::Loaders::Loader#load_rails_engines'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/loader.rb:172:in 'Tapioca::Loaders::Loader#with_rails_application'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Loader#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/loader.rb:92:in 'Tapioca::Loaders::Loader#load_rails_engines'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Loader#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/loader.rb:38:in 'Tapioca::Loaders::Loader#load_bundle'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Loader#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/gem.rb:63:in 'Tapioca::Loaders::Gem#require_gem_file'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Gem#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/gem.rb:35:in 'Tapioca::Loaders::Gem#load'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Gem#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/loaders/gem.rb:29:in 'Tapioca::Loaders::Gem.load_application'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Loaders::Gem._on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/commands/abstract_gem.rb:159:in 'block in Tapioca::Commands::AbstractGem#perform_additions'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/shell/basic.rb:46:in 'Thor::Shell::Basic#indent'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/commands/abstract_gem.rb:155:in 'Tapioca::Commands::AbstractGem#perform_additions'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Commands::AbstractGem#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/commands/gem_sync.rb:13:in 'Tapioca::Commands::GemSync#execute'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Commands::GemSync#_on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/commands/command.rb:27:in 'block in Tapioca::Commands::Command#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca.rb:24:in 'block in Tapioca.silence_warnings'
	from /Users/mattbee/.rubies/ruby-3.4.2/lib/ruby/3.4.0/rubygems/user_interaction.rb:46:in 'Gem::DefaultUserInteraction.use_ui'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca.rb:23:in 'Tapioca.silence_warnings'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/commands/command.rb:26:in 'Tapioca::Commands::Command#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/cli.rb:314:in 'Tapioca::Cli#gem'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/command.rb:28:in 'Thor::Command#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor.rb:538:in 'Thor.dispatch'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/invocation.rb:116:in 'Thor::Invocation#invoke'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/cli.rb:32:in 'block in Tapioca::Cli#init'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/runtime/trackers.rb:26:in 'Tapioca::Runtime::Trackers.with_trackers_enabled'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'UnboundMethod#bind_call'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/sorbet-runtime-0.5.12210/lib/types/private/methods/_methods.rb:279:in 'block in Tapioca::Runtime::Trackers._on_method_added'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/lib/tapioca/cli.rb:29:in 'Tapioca::Cli#init'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/command.rb:28:in 'Thor::Command#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor.rb:538:in 'Thor.dispatch'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/thor-1.3.2/lib/thor/base.rb:584:in 'Thor::Base::ClassMethods#start'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/tapioca-0.16.11/exe/tapioca:30:in '<top (required)>'
	from /Users/mattbee/.gem/ruby/3.4.2/bin/tapioca:25:in 'Kernel#load'
	from /Users/mattbee/.gem/ruby/3.4.2/bin/tapioca:25:in '<top (required)>'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:59:in 'Kernel.load'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli.rb:452:in 'Bundler::CLI#exec'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/exe/bundle:28:in 'block in <top (required)>'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
	from /Users/mattbee/.gem/ruby/3.4.2/gems/bundler-2.6.9/exe/bundle:20:in '<top (required)>'
	from /Users/mattbee/.gem/ruby/3.4.2/bin/bundle:25:in 'Kernel#load'
	from /Users/mattbee/.gem/ruby/3.4.2/bin/bundle:25:in '<main>'
```

**Comment by KaanOzkan** [comment]
Fixed in v0.17.0 https://github.com/Shopify/tapioca/commit/f4d2ba349652b2fb895f01ec95f6925916a417ad
