### ISSUE TITLE
tapioca gem fails with bundler 2.6.0

### ISSUE THREAD

**Issue by bmulholland** [Shopify/tapioca#2132]
Works fine with bundler 2.5.23, but when upgrading to bundler 2.6.0:

```
% be tapioca gem
bundler: failed to load command: tapioca (/Users/bmulholland/.local/share/mise/installs/ruby/3.3.6/bin/tapioca)
/Users/bmulholland/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/bundler-2.6.0/lib/bundler/spec_set.rb:143:in `missing_specs': undefined method `flat_map' for nil (NoMethodError)

      @materializations.flat_map(&:completely_missing_specs)
                       ^^^^^^^^^
	from /Users/bmulholland/.local/share/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/tapioca-0.16.5/lib/tapioca/gemfile.rb:71:in `materialize_deps'
```

**Comment by stathis-alexander** [comment]
https://github.com/Shopify/tapioca/pull/2129

**Comment by bmulholland** [comment]
Thanks! Searched issues but not PRs 🤦‍♂️

**Comment by swiknaba** [comment]
https://github.com/rubygems/rubygems/issues/8338
