### ISSUE TITLE
rails_generators.rb:52:in decorate: undefined method `arguments` for XPath:Module (NoMethodError)

### ISSUE THREAD

**Issue by Overload119** [Shopify/tapioca#676]
This is a new error I got after upgrading from 0.5.0 -> 0.6.0.

<details>

```
Traceback (most recent call last):
	33: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
	32: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
	31: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/bin/tapioca:23:in `<main>'
	30: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/bin/tapioca:23:in `load'
	29: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/exe/tapioca:23:in `<top (required)>'
	28: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	27: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	26: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	24: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/cli.rb:123:in `dsl'
	23: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	22: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `bind_call'
	21: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca.rb:17:in `silence_warnings'
	20: from /Users/amirsharif/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
	19: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca.rb:18:in `block in silence_warnings'
	18: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/cli.rb:124:in `block in dsl'
	17: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	16: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `bind_call'
	15: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/generators/dsl.rb:83:in `generate'
	14: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	13: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `bind_call'
	12: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl_compiler.rb:65:in `run'
	11: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	10: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `bind_call'
	 9: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/executor.rb:36:in `run_in_parallel'
	 8: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/executor.rb:36:in `map'
	 7: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/executor.rb:36:in `block in run_in_parallel'
	 6: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl_compiler.rb:66:in `block in run'
	 5: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl_compiler.rb:116:in `rbi_for_constant'
	 4: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl_compiler.rb:116:in `each'
	 3: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl_compiler.rb:118:in `block in rbi_for_constant'
	 2: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
	 1: from /Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/sorbet-runtime-0.5.9464/lib/types/private/methods/_methods.rb:272:in `bind_call'
/Users/amirsharif/.rvm/gems/ruby-2.7.4/gems/tapioca-0.6.0/lib/tapioca/compilers/dsl/rails_generators.rb:52:in `decorate': undefined method `arguments' for XPath:Module (NoMethodError)
```

</details>

**Comment by Overload119** [comment]
Unblocked with 

`tapioca dsl --exclude RailsGenerators`

Curiously, it did produce this:

```
# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `XPath`.
# Please instead update this file by running `bin/tapioca dsl XPath`.

module XPath
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
```

This is related to the `nokogiri` gem.

**Comment by paracycle** [comment]
Thanks for reporting this. Unfortunately, the `XPath` module responds to all messages, so unless we are careful, we end up getting into situations like this.

I'll make sure to get the Rails generators compiler fixed and will ensure that URL helpers compiler foes not consider XPath to include url helpers either.

For the time being, you should be able to add the exclude in the Tapioca config to make sure it is always applied: https://github.com/Shopify/tapioca#configuration
